# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba761c4d81cdeee9c50f98e0b4e58412677371652becc5a0e0436d6b0b9543de6aad2e2c64f8e0bfc93c12b6cb1c67ece8c23ef09b866a05ae53ecbe8a6224aa

test:
  secret_key_base: b204a2f0e4b306f8de14967c11e3b5b9f865b905219abfff3cb2e3cee946a45c14f6aa18f5c3ba3bc91e4ee40062ec9cab44166efe66687216ee5b73f6add7f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
